{
    'name': 'AGB Communication Attendance Dashboard',
    'version': '1.0.0',
    'description': 'Employee Attendance Dashboard for AGB Communication Myanmar',
    'author': 'AGB Communication',
    'website': 'https://agbcommunication.com',
    'category': 'Human Resources',
    'depends': ['base', 'hr', 'hr_attendance'],
    'data': [
        'security/ir.model.access.csv',
        'views/attendance_dashboard_templates.xml',
        'views/register_template.xml',
        'views/leave_request_form_template.xml',
        'views/employee_profile_template.xml',
        'views/leave_balance.xml',
        'views/hr_leave_tree.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'AGB_HR/static/src/css/attendance_dashboard.css',
            'AGB_HR/static/src/js/attendance_dashboard.js',
            'AGB_HR/static/src/css/register.css',
            'AGB_HR/static/src/js/register.js',
            'AGB_HR/static/src/js/leave_request.js',
            'AGB_HR/static/src/css/leave_request.css',
            'AGB_HR/static/src/js/profile.js',
            'AGB_HR/static/src/css/profile.css',
            'AGB_HR/static/src/css/leave_balance.css',
            'AGB_HR/static/src/js/leave_balance.js',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': True,
}
